include: package:lints/recommended.yaml

analyzer:
  exclude: [assets/**, lib/**/*.g.dart]
  language:
    strict-casts: false
    strict-inference: false
    strict-raw-types: false
  strong-mode:
    implicit-dynamic: true
  errors:
    dead_code: warning

linter:
  rules:
    always_use_package_imports: true
    avoid_empty_else: true
    avoid_print: true
    cancel_subscriptions: true
    empty_statements: true
    control_flow_in_finally: true
    hash_and_equals: true
    no_duplicate_case_values: true
    no_logic_in_create_state: true
    unnecessary_statements: true
    unnecessary_new: true
    valid_regexps: true
    avoid_returning_null_for_void: true
    avoid_unnecessary_containers: true
    empty_catches: true
    implementation_imports: true
    prefer_contains: true
    prefer_generic_function_type_aliases: true
    prefer_if_null_operators: true
    prefer_is_empty: true
    prefer_interpolation_to_compose_strings: true
    prefer_is_not_operator: true
    prefer_spread_collections: true
    recursive_getters: true
    unnecessary_brace_in_string_interps: true
    unnecessary_nullable_for_final_variable_declarations: true
    unnecessary_string_interpolations: true
